Repository BurlingtonCodeAcademy/sdb-summer-2021-curriculum, pull requests merged in 2022-02, with the labels that each got.

#14 Apply recommendations from lab review for Hello Frenemy in Feb-2022
  week-1/labs/hello_frenemy.md
Labels: needs-review

#4 Manipulating Data
  week-1/manipulating_data.md
  week-1/variables.md
Labels: ready-for-merge

#8 Apply recommendations from lab review for Feb-2022
  week-1/labs/divisible.md
Labels: ready-for-merge

#11 Apply recommendations from lab review for Divisible lab in Feb-2022
  week-1/labs/capitalize.md
Labels: needs-review

#12 Apply recommendations from lab review for One Potato lab in Feb-2022
  week-1/labs/one_potato.md
Labels: needs-review

#9 Unit-1 Intro Input Output Improvements
  week-1/input_and_output.md
Labels: ready-for-merge

#16 Unit-1 Arrays Improvements
  week-2/intro_to_arrays.md
Labels: needs-review

#19 Simplify Objects Slides
  week-2/objects.md
Labels: documentation, enhancement

#20 Object Methods Improvements
  week-2/methods.md
Labels: ready-for-merge

#18 Update capitalize.md
  week-1/labs/capitalize.md
Labels: needs-review

#25 Apply recommended changes from the review of Menu Order lab
  week-2/labs/menu_order.md
Labels: needs-review

#26 lab/improve class gpa
  week-2/labs/class_gpa.md
Labels: needs-review

#27 Apply changes to Walkway lab, update to new format
  week-2/labs/walkway.md
Labels: needs-review

#28 Improve the Cake Constructor lab, update to new format
  week-2/labs/cake_constructor.md
Labels: needs-review

#29 Improve the Tag Search lab, update to new format
  week-2/labs/tag_search.md
Labels: needs-review

#24 Simplify Object Patterns Lesson
  week-2/object_patterns.md
Labels: ready-for-merge

#30 Begin improvements for Object-Oriented Design
  week-2/oo_design.md
Labels: needs-review

#31 CSS Layout Lesson Improvements
  week-3/css_layout.md
Labels: enhancement

#32 Flexbox Layout Lesson Improvements
  week-3/flexbox_layout.md
Labels: enhancement

#35 Improve HTML Lesson content
  week-3/html.md
Labels: enhancement, ready-for-merge

#34 Improve How the Web Works Lesson content
  week-3/how_the_web_works.md
Labels: enhancement, ready-for-merge

#36 Apply improvements from the lab review
  week-3/labs/hello_styles.md
Labels: enhancement, ready-for-merge

#37 Improve the image gallery lab
  week-3/labs/image_gallery.md
Labels: enhancement, ready-for-merge

#38 Improve the Article Preview lab
  week-3/labs/article_preview.md
Labels: enhancement, ready-for-merge

#43 Intro to DOM Improvements
  week-4/intro_to_the_dom.md
Labels: enhancement, needs-review, ready-for-merge

#39 DOM Debugging Improvements
  week-4/dom_debugging.md
Labels: enhancement, ready-for-merge

#40 Events and Event Listeners Improvements
  week-4/events_and_event_listeners.md
Labels: enhancement, ready-for-merge

#41 Fetching and AJAX Improvements
  week-4/fetching_and_ajax.md
Labels: enhancement, ready-for-merge

#42 Inherent Events Improvements
  week-4/inherent_events.md
Labels: enhancement, ready-for-merge

#44 Update the timer lab instructions to new format
  week-4/labs/timer.md
Labels: documentation, enhancement
